config/routes.rb
Rails.application.routes.draw do
 
  get 'sessions/new'

  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'attendants#new'
  post 'signup',   to: 'attendants#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :attendants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendant.rb
class Attendant < ApplicationRecord
	before_save { self.email = email.downcase }
	validates(:first_name, presence: true, length: { maximum: 50})
	validates(:last_name, presence: true, length: { maximum: 50})
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates(:email, presence: true, length: {maximum: 255},
		format: { with: VALID_EMAIL_REGEX }, 
		uniqueness: { case_sensitive: false})
	validates(:gender, presence: true)
	validates(:english_level, presence: true)
	has_secure_password
	validates(:password, presence: true, length: { minimum: 6 })
	# Returns the hash digest of the given string.
  def Attendant.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/attendants_controller.rb
class AttendantsController < ApplicationController
  def show
  	@attendant = Attendant.find(params[:id])
  end
  def new
  	@attendant=Attendant.new
  end
  def create
  	@attendant=Attendant.new(attendant_params)
  	if @attendant.save
      log_in @attendant
  		flash[:success] = "Welcome to the English discussion portal!"
  		redirect_to @attendant
  		
  	else
  		render 'new'
  		
  	end
  	
  end

  private
  def attendant_params
  	params.require(:attendant).permit(:first_name, :last_name,
  	 :gender, :english_level, :joining_reason, :email, 
  	 :password, :password_confirmation)
  	
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    attendant = Attendant.find_by(email: params[:session][:email].downcase)
    if attendant && attendant.authenticate(params[:session][:password])
    	log_in attendant
    	redirect_to attendant
      # Log the user in and redirect to the user's show page.
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "English Discussion Portal"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/attendants_helper.rb
module AttendantsHelper
	 # Returns the Gravatar for the given Attendant.
  def gravatar_for(attendant, size: 80)
    gravatar_id = Digest::MD5::hexdigest(attendant.email.downcase)
    #size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/
    #{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: attendant.first_name + " " + attendant.last_name, class: "gravatar")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(attendant)
    session[:attendant_id] = attendant.id
  end

  # Returns the current logged-in user (if any).
  def current_attendant
    @current_attendant ||= Attendant.find_by(id: session[:attendant_id])
  end
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_attendant.nil?
  end
  # Logs out the current user.
  def log_out
    session.delete(:attendant_id)
    @current_attendant = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/attendants/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@attendant, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form_control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form_control' %>

      <%= f.label :gender %>
      <%= f.text_field :gender, class: 'form_control' %>

      <%= f.label :english_level %>
      <%= f.text_field :english_level, class: 'form_control' %>

      <%= f.label :joining_reason %>
      <%= f.text_area :joining_reason, class: 'form_control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form_control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form_control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form_control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/attendants/show.html.erb
<% provide(:title, @attendant.first_name + " " + @attendant.last_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="attendant_info">
<h1>
  <%= gravatar_for @attendant %>
  <%= @attendant.first_name %>
</h1>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small><em>
    All rights reserved to English Discussion Portal - Frank Atukunda</em></small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "English Discussion Portal", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Attendants", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_attendant %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>

      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
        
      end
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @attendant.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@attendant.errors.count, "error") %>.
    </div>
    <ul>
    <% @attendant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The English discussion portal Istanbul brings together students who are interested in improving their English language through discussing different topics. On a particular day, a discussion is arranged and those interested register for the discussion.
  
</p>
  

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Frank Atukunda
  fatukunda@gmail.com
  +905060663656
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>English Discussion Portal Istanbul</h1>

  <h2>
    Welcome to the English discussion portal. Feel free to register for our upcoming discussions. Come meet up with people who are trying to achieve the same goal i.e speak English like natives.
  </h2>

   <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
  
  